# Generated by Django 3.0.2 on 2020-01-15 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bancomer', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('applied', 'description')},
        ),
    ]
